// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createScheduleSuggestion = `-- name: CreateScheduleSuggestion :one
INSERT INTO schedule_suggestions (user_message, llm_response, week_offset, changes_made)
VALUES (?, ?, ?, ?)
RETURNING id, user_message, llm_response, week_offset, changes_made, created_at
`

type CreateScheduleSuggestionParams struct {
	UserMessage string        `json:"user_message"`
	LlmResponse string        `json:"llm_response"`
	WeekOffset  sql.NullInt64 `json:"week_offset"`
	ChangesMade sql.NullBool  `json:"changes_made"`
}

func (q *Queries) CreateScheduleSuggestion(ctx context.Context, arg CreateScheduleSuggestionParams) (ScheduleSuggestion, error) {
	row := q.db.QueryRowContext(ctx, createScheduleSuggestion,
		arg.UserMessage,
		arg.LlmResponse,
		arg.WeekOffset,
		arg.ChangesMade,
	)
	var i ScheduleSuggestion
	err := row.Scan(
		&i.ID,
		&i.UserMessage,
		&i.LlmResponse,
		&i.WeekOffset,
		&i.ChangesMade,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldSuggestions = `-- name: DeleteOldSuggestions :exec
DELETE FROM schedule_suggestions
WHERE created_at < datetime('now', '-' || ? || ' days')
`

func (q *Queries) DeleteOldSuggestions(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldSuggestions, dollar_1)
	return err
}

const getRecentSuggestions = `-- name: GetRecentSuggestions :many
SELECT id, user_message, llm_response, week_offset, changes_made, created_at FROM schedule_suggestions
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetRecentSuggestions(ctx context.Context, limit int64) ([]ScheduleSuggestion, error) {
	rows, err := q.db.QueryContext(ctx, getRecentSuggestions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleSuggestion{}
	for rows.Next() {
		var i ScheduleSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.UserMessage,
			&i.LlmResponse,
			&i.WeekOffset,
			&i.ChangesMade,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestionsForWeek = `-- name: GetSuggestionsForWeek :many
SELECT id, user_message, llm_response, week_offset, changes_made, created_at FROM schedule_suggestions
WHERE week_offset = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetSuggestionsForWeekParams struct {
	WeekOffset sql.NullInt64 `json:"week_offset"`
	Limit      int64         `json:"limit"`
}

func (q *Queries) GetSuggestionsForWeek(ctx context.Context, arg GetSuggestionsForWeekParams) ([]ScheduleSuggestion, error) {
	rows, err := q.db.QueryContext(ctx, getSuggestionsForWeek, arg.WeekOffset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleSuggestion{}
	for rows.Next() {
		var i ScheduleSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.UserMessage,
			&i.LlmResponse,
			&i.WeekOffset,
			&i.ChangesMade,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
