// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: completions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCompletion = `-- name: CreateCompletion :one
INSERT INTO completions (task_instance_id, completed_by, actual_mins)
VALUES (?, ?, ?)
RETURNING id, task_instance_id, completed_by, completed_at, actual_mins
`

type CreateCompletionParams struct {
	TaskInstanceID int64         `json:"task_instance_id"`
	CompletedBy    string        `json:"completed_by"`
	ActualMins     sql.NullInt64 `json:"actual_mins"`
}

func (q *Queries) CreateCompletion(ctx context.Context, arg CreateCompletionParams) (Completion, error) {
	row := q.db.QueryRowContext(ctx, createCompletion, arg.TaskInstanceID, arg.CompletedBy, arg.ActualMins)
	var i Completion
	err := row.Scan(
		&i.ID,
		&i.TaskInstanceID,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.ActualMins,
	)
	return i, err
}

const deleteCompletion = `-- name: DeleteCompletion :exec
DELETE FROM completions
WHERE task_instance_id = ?
`

func (q *Queries) DeleteCompletion(ctx context.Context, taskInstanceID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCompletion, taskInstanceID)
	return err
}

const deleteOldCompletions = `-- name: DeleteOldCompletions :exec
DELETE FROM completions
WHERE completed_at < date('now', '-' || ? || ' days')
`

func (q *Queries) DeleteOldCompletions(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldCompletions, dollar_1)
	return err
}

const getCategoryStats = `-- name: GetCategoryStats :many
SELECT
    t.category,
    COUNT(ti.id) as scheduled_count,
    SUM(CASE WHEN c.id IS NOT NULL THEN 1 ELSE 0 END) as completed_count
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
LEFT JOIN completions c ON c.task_instance_id = ti.id
WHERE ti.scheduled_date >= ? AND ti.scheduled_date <= ?
GROUP BY t.category
ORDER BY t.category
`

type GetCategoryStatsParams struct {
	ScheduledDate   time.Time `json:"scheduled_date"`
	ScheduledDate_2 time.Time `json:"scheduled_date_2"`
}

type GetCategoryStatsRow struct {
	Category       string          `json:"category"`
	ScheduledCount int64           `json:"scheduled_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
}

func (q *Queries) GetCategoryStats(ctx context.Context, arg GetCategoryStatsParams) ([]GetCategoryStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryStats, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryStatsRow{}
	for rows.Next() {
		var i GetCategoryStatsRow
		if err := rows.Scan(&i.Category, &i.ScheduledCount, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletion = `-- name: GetCompletion :one
SELECT id, task_instance_id, completed_by, completed_at, actual_mins FROM completions
WHERE task_instance_id = ?
LIMIT 1
`

func (q *Queries) GetCompletion(ctx context.Context, taskInstanceID int64) (Completion, error) {
	row := q.db.QueryRowContext(ctx, getCompletion, taskInstanceID)
	var i Completion
	err := row.Scan(
		&i.ID,
		&i.TaskInstanceID,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.ActualMins,
	)
	return i, err
}

const getCompletionByInstance = `-- name: GetCompletionByInstance :one
SELECT id, task_instance_id, completed_by, completed_at, actual_mins FROM completions
WHERE task_instance_id = ?
LIMIT 1
`

func (q *Queries) GetCompletionByInstance(ctx context.Context, taskInstanceID int64) (Completion, error) {
	row := q.db.QueryRowContext(ctx, getCompletionByInstance, taskInstanceID)
	var i Completion
	err := row.Scan(
		&i.ID,
		&i.TaskInstanceID,
		&i.CompletedBy,
		&i.CompletedAt,
		&i.ActualMins,
	)
	return i, err
}

const getCompletionStats = `-- name: GetCompletionStats :many
SELECT
    ti.assigned_to,
    COUNT(ti.id) as scheduled_count,
    SUM(CASE WHEN c.id IS NOT NULL THEN 1 ELSE 0 END) as completed_count,
    SUM(CASE WHEN ti.counts_toward_weekly THEN t.estimated_mins ELSE 0 END) as scheduled_mins,
    SUM(CASE WHEN c.id IS NOT NULL AND ti.counts_toward_weekly THEN t.estimated_mins ELSE 0 END) as completed_mins
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
LEFT JOIN completions c ON c.task_instance_id = ti.id
WHERE ti.scheduled_date >= ? AND ti.scheduled_date <= ?
GROUP BY ti.assigned_to
`

type GetCompletionStatsParams struct {
	ScheduledDate   time.Time `json:"scheduled_date"`
	ScheduledDate_2 time.Time `json:"scheduled_date_2"`
}

type GetCompletionStatsRow struct {
	AssignedTo     string          `json:"assigned_to"`
	ScheduledCount int64           `json:"scheduled_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
	ScheduledMins  sql.NullFloat64 `json:"scheduled_mins"`
	CompletedMins  sql.NullFloat64 `json:"completed_mins"`
}

func (q *Queries) GetCompletionStats(ctx context.Context, arg GetCompletionStatsParams) ([]GetCompletionStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCompletionStats, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompletionStatsRow{}
	for rows.Next() {
		var i GetCompletionStatsRow
		if err := rows.Scan(
			&i.AssignedTo,
			&i.ScheduledCount,
			&i.CompletedCount,
			&i.ScheduledMins,
			&i.CompletedMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyCompletionStats = `-- name: GetWeeklyCompletionStats :many
SELECT week_start, total_count, completed_count
FROM (
    SELECT
        ti.week_start_date as week_start,
        COUNT(ti.id) as total_count,
        SUM(CASE WHEN c.id IS NOT NULL THEN 1 ELSE 0 END) as completed_count
    FROM task_instances ti
    LEFT JOIN completions c ON c.task_instance_id = ti.id
    WHERE ti.week_start_date <= date('now')
    GROUP BY ti.week_start_date
    ORDER BY ti.week_start_date DESC
    LIMIT 4
)
ORDER BY week_start ASC
`

type GetWeeklyCompletionStatsRow struct {
	WeekStart      time.Time       `json:"week_start"`
	TotalCount     int64           `json:"total_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
}

func (q *Queries) GetWeeklyCompletionStats(ctx context.Context) ([]GetWeeklyCompletionStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyCompletionStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeeklyCompletionStatsRow{}
	for rows.Next() {
		var i GetWeeklyCompletionStatsRow
		if err := rows.Scan(&i.WeekStart, &i.TotalCount, &i.CompletedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionsByDateRange = `-- name: ListCompletionsByDateRange :many
SELECT c.id, c.task_instance_id, c.completed_by, c.completed_at, c.actual_mins, ti.assigned_to, t.name
FROM completions c
JOIN task_instances ti ON c.task_instance_id = ti.id
JOIN tasks t ON ti.task_id = t.id
WHERE ti.scheduled_date >= ? AND ti.scheduled_date <= ?
ORDER BY c.completed_at DESC
`

type ListCompletionsByDateRangeParams struct {
	ScheduledDate   time.Time `json:"scheduled_date"`
	ScheduledDate_2 time.Time `json:"scheduled_date_2"`
}

type ListCompletionsByDateRangeRow struct {
	ID             int64         `json:"id"`
	TaskInstanceID int64         `json:"task_instance_id"`
	CompletedBy    string        `json:"completed_by"`
	CompletedAt    sql.NullTime  `json:"completed_at"`
	ActualMins     sql.NullInt64 `json:"actual_mins"`
	AssignedTo     string        `json:"assigned_to"`
	Name           string        `json:"name"`
}

func (q *Queries) ListCompletionsByDateRange(ctx context.Context, arg ListCompletionsByDateRangeParams) ([]ListCompletionsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompletionsByDateRange, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletionsByDateRangeRow{}
	for rows.Next() {
		var i ListCompletionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskInstanceID,
			&i.CompletedBy,
			&i.CompletedAt,
			&i.ActualMins,
			&i.AssignedTo,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
