// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const checkDuplicateInstance = `-- name: CheckDuplicateInstance :one
SELECT COUNT(*) FROM task_instances
WHERE task_id = ? AND scheduled_date = ? AND brought_forward = FALSE
`

type CheckDuplicateInstanceParams struct {
	TaskID        int64     `json:"task_id"`
	ScheduledDate time.Time `json:"scheduled_date"`
}

func (q *Queries) CheckDuplicateInstance(ctx context.Context, arg CheckDuplicateInstanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateInstance, arg.TaskID, arg.ScheduledDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInstances = `-- name: CountInstances :one
SELECT COUNT(*) FROM task_instances
`

func (q *Queries) CountInstances(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInstances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO task_instances (
    task_id, scheduled_date, original_scheduled_date, assigned_to,
    week_start_date, brought_forward, brought_forward_by, counts_toward_weekly
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, task_id, scheduled_date, original_scheduled_date, assigned_to, week_start_date, brought_forward, brought_forward_by, counts_toward_weekly, created_at
`

type CreateInstanceParams struct {
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (TaskInstance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.TaskID,
		arg.ScheduledDate,
		arg.OriginalScheduledDate,
		arg.AssignedTo,
		arg.WeekStartDate,
		arg.BroughtForward,
		arg.BroughtForwardBy,
		arg.CountsTowardWeekly,
	)
	var i TaskInstance
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ScheduledDate,
		&i.OriginalScheduledDate,
		&i.AssignedTo,
		&i.WeekStartDate,
		&i.BroughtForward,
		&i.BroughtForwardBy,
		&i.CountsTowardWeekly,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldInstances = `-- name: DeleteOldInstances :exec
DELETE FROM task_instances
WHERE scheduled_date < date('now', '-90 days')
`

func (q *Queries) DeleteOldInstances(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldInstances)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT ti.id, ti.task_id, ti.scheduled_date, ti.original_scheduled_date, ti.assigned_to, ti.week_start_date, ti.brought_forward, ti.brought_forward_by, ti.counts_toward_weekly, ti.created_at, t.name, t.category, t.estimated_mins
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
WHERE ti.id = ?
LIMIT 1
`

type GetInstanceRow struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	Name                  string         `json:"name"`
	Category              string         `json:"category"`
	EstimatedMins         int64          `json:"estimated_mins"`
}

func (q *Queries) GetInstance(ctx context.Context, id int64) (GetInstanceRow, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i GetInstanceRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ScheduledDate,
		&i.OriginalScheduledDate,
		&i.AssignedTo,
		&i.WeekStartDate,
		&i.BroughtForward,
		&i.BroughtForwardBy,
		&i.CountsTowardWeekly,
		&i.CreatedAt,
		&i.Name,
		&i.Category,
		&i.EstimatedMins,
	)
	return i, err
}

const getInstanceWithTask = `-- name: GetInstanceWithTask :one
SELECT ti.id, ti.task_id, ti.scheduled_date, ti.original_scheduled_date, ti.assigned_to, ti.week_start_date, ti.brought_forward, ti.brought_forward_by, ti.counts_toward_weekly, ti.created_at, t.name as task_name, t.category as task_category, t.estimated_mins
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
WHERE ti.id = ?
LIMIT 1
`

type GetInstanceWithTaskRow struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	TaskName              string         `json:"task_name"`
	TaskCategory          string         `json:"task_category"`
	EstimatedMins         int64          `json:"estimated_mins"`
}

func (q *Queries) GetInstanceWithTask(ctx context.Context, id int64) (GetInstanceWithTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getInstanceWithTask, id)
	var i GetInstanceWithTaskRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ScheduledDate,
		&i.OriginalScheduledDate,
		&i.AssignedTo,
		&i.WeekStartDate,
		&i.BroughtForward,
		&i.BroughtForwardBy,
		&i.CountsTowardWeekly,
		&i.CreatedAt,
		&i.TaskName,
		&i.TaskCategory,
		&i.EstimatedMins,
	)
	return i, err
}

const getNextInstanceForTask = `-- name: GetNextInstanceForTask :one
SELECT ti.id, ti.task_id, ti.scheduled_date, ti.original_scheduled_date, ti.assigned_to, ti.week_start_date, ti.brought_forward, ti.brought_forward_by, ti.counts_toward_weekly, ti.created_at, t.name, t.category, t.estimated_mins
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
WHERE ti.task_id = ?
  AND ti.scheduled_date > ?
  AND ti.brought_forward = FALSE
ORDER BY ti.scheduled_date
LIMIT 1
`

type GetNextInstanceForTaskParams struct {
	TaskID        int64     `json:"task_id"`
	ScheduledDate time.Time `json:"scheduled_date"`
}

type GetNextInstanceForTaskRow struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	Name                  string         `json:"name"`
	Category              string         `json:"category"`
	EstimatedMins         int64          `json:"estimated_mins"`
}

func (q *Queries) GetNextInstanceForTask(ctx context.Context, arg GetNextInstanceForTaskParams) (GetNextInstanceForTaskRow, error) {
	row := q.db.QueryRowContext(ctx, getNextInstanceForTask, arg.TaskID, arg.ScheduledDate)
	var i GetNextInstanceForTaskRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ScheduledDate,
		&i.OriginalScheduledDate,
		&i.AssignedTo,
		&i.WeekStartDate,
		&i.BroughtForward,
		&i.BroughtForwardBy,
		&i.CountsTowardWeekly,
		&i.CreatedAt,
		&i.Name,
		&i.Category,
		&i.EstimatedMins,
	)
	return i, err
}

const listFutureInstances = `-- name: ListFutureInstances :many
SELECT ti.id, ti.task_id, ti.scheduled_date, ti.original_scheduled_date, ti.assigned_to, ti.week_start_date, ti.brought_forward, ti.brought_forward_by, ti.counts_toward_weekly, ti.created_at, t.name, t.category, t.estimated_mins
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
WHERE ti.scheduled_date > ?
  AND ti.brought_forward = FALSE
  AND (ti.assigned_to = ? OR t.default_assignee = 'Both')
ORDER BY ti.scheduled_date, t.name
`

type ListFutureInstancesParams struct {
	ScheduledDate time.Time `json:"scheduled_date"`
	AssignedTo    string    `json:"assigned_to"`
}

type ListFutureInstancesRow struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	Name                  string         `json:"name"`
	Category              string         `json:"category"`
	EstimatedMins         int64          `json:"estimated_mins"`
}

func (q *Queries) ListFutureInstances(ctx context.Context, arg ListFutureInstancesParams) ([]ListFutureInstancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFutureInstances, arg.ScheduledDate, arg.AssignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFutureInstancesRow{}
	for rows.Next() {
		var i ListFutureInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledDate,
			&i.OriginalScheduledDate,
			&i.AssignedTo,
			&i.WeekStartDate,
			&i.BroughtForward,
			&i.BroughtForwardBy,
			&i.CountsTowardWeekly,
			&i.CreatedAt,
			&i.Name,
			&i.Category,
			&i.EstimatedMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByDateRange = `-- name: ListInstancesByDateRange :many
SELECT ti.id, ti.task_id, ti.scheduled_date, ti.original_scheduled_date, ti.assigned_to, ti.week_start_date, ti.brought_forward, ti.brought_forward_by, ti.counts_toward_weekly, ti.created_at, t.name, t.category, t.estimated_mins,
       c.id as completion_id, c.completed_by, c.completed_at
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
LEFT JOIN completions c ON c.task_instance_id = ti.id
WHERE ti.scheduled_date >= ? AND ti.scheduled_date <= ?
ORDER BY ti.scheduled_date, ti.assigned_to, t.name
`

type ListInstancesByDateRangeParams struct {
	ScheduledDate   time.Time `json:"scheduled_date"`
	ScheduledDate_2 time.Time `json:"scheduled_date_2"`
}

type ListInstancesByDateRangeRow struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	Name                  string         `json:"name"`
	Category              string         `json:"category"`
	EstimatedMins         int64          `json:"estimated_mins"`
	CompletionID          sql.NullInt64  `json:"completion_id"`
	CompletedBy           sql.NullString `json:"completed_by"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
}

func (q *Queries) ListInstancesByDateRange(ctx context.Context, arg ListInstancesByDateRangeParams) ([]ListInstancesByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstancesByDateRange, arg.ScheduledDate, arg.ScheduledDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstancesByDateRangeRow{}
	for rows.Next() {
		var i ListInstancesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledDate,
			&i.OriginalScheduledDate,
			&i.AssignedTo,
			&i.WeekStartDate,
			&i.BroughtForward,
			&i.BroughtForwardBy,
			&i.CountsTowardWeekly,
			&i.CreatedAt,
			&i.Name,
			&i.Category,
			&i.EstimatedMins,
			&i.CompletionID,
			&i.CompletedBy,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByWeek = `-- name: ListInstancesByWeek :many
SELECT ti.id, ti.task_id, ti.scheduled_date, ti.original_scheduled_date, ti.assigned_to, ti.week_start_date, ti.brought_forward, ti.brought_forward_by, ti.counts_toward_weekly, ti.created_at, t.name as task_name, t.category as task_category, t.estimated_mins,
       c.id as completion_id, c.completed_by, c.completed_at
FROM task_instances ti
JOIN tasks t ON ti.task_id = t.id
LEFT JOIN completions c ON c.task_instance_id = ti.id
WHERE ti.week_start_date = ?
ORDER BY ti.assigned_to, ti.scheduled_date, t.name
`

type ListInstancesByWeekRow struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	TaskName              string         `json:"task_name"`
	TaskCategory          string         `json:"task_category"`
	EstimatedMins         int64          `json:"estimated_mins"`
	CompletionID          sql.NullInt64  `json:"completion_id"`
	CompletedBy           sql.NullString `json:"completed_by"`
	CompletedAt           sql.NullTime   `json:"completed_at"`
}

func (q *Queries) ListInstancesByWeek(ctx context.Context, weekStartDate time.Time) ([]ListInstancesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listInstancesByWeek, weekStartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstancesByWeekRow{}
	for rows.Next() {
		var i ListInstancesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledDate,
			&i.OriginalScheduledDate,
			&i.AssignedTo,
			&i.WeekStartDate,
			&i.BroughtForward,
			&i.BroughtForwardBy,
			&i.CountsTowardWeekly,
			&i.CreatedAt,
			&i.TaskName,
			&i.TaskCategory,
			&i.EstimatedMins,
			&i.CompletionID,
			&i.CompletedBy,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInstances = `-- name: ListTaskInstances :many
SELECT id, task_id, scheduled_date, original_scheduled_date, assigned_to, week_start_date, brought_forward, brought_forward_by, counts_toward_weekly, created_at FROM task_instances
ORDER BY week_start_date, scheduled_date
`

func (q *Queries) ListTaskInstances(ctx context.Context) ([]TaskInstance, error) {
	rows, err := q.db.QueryContext(ctx, listTaskInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskInstance{}
	for rows.Next() {
		var i TaskInstance
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledDate,
			&i.OriginalScheduledDate,
			&i.AssignedTo,
			&i.WeekStartDate,
			&i.BroughtForward,
			&i.BroughtForwardBy,
			&i.CountsTowardWeekly,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskInstanceAssignment = `-- name: UpdateTaskInstanceAssignment :exec
UPDATE task_instances
SET assigned_to = ?
WHERE id = ?
`

type UpdateTaskInstanceAssignmentParams struct {
	AssignedTo string `json:"assigned_to"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateTaskInstanceAssignment(ctx context.Context, arg UpdateTaskInstanceAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskInstanceAssignment, arg.AssignedTo, arg.ID)
	return err
}
