// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package sqlc

import (
	"context"
)

const countMealUsage = `-- name: CountMealUsage :one
SELECT COUNT(*) FROM shopping_items
WHERE meal IS NOT NULL AND LOWER(meal) = LOWER(?)
`

func (q *Queries) CountMealUsage(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMealUsage, lower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (name)
VALUES (?)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateMeal(ctx context.Context, name string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal, name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE id = ?
`

func (q *Queries) DeleteMeal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeal, id)
	return err
}

const getMeal = `-- name: GetMeal :one
SELECT id, name, created_at, updated_at FROM meals
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetMeal(ctx context.Context, id int64) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealByName = `-- name: GetMealByName :one
SELECT id, name, created_at, updated_at FROM meals
WHERE LOWER(name) = LOWER(?)
LIMIT 1
`

func (q *Queries) GetMealByName(ctx context.Context, lower string) (Meal, error) {
	row := q.db.QueryRowContext(ctx, getMealByName, lower)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMeals = `-- name: ListMeals :many
SELECT id, name, created_at, updated_at FROM meals
ORDER BY name
`

func (q *Queries) ListMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.QueryContext(ctx, listMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, created_at, updated_at
`

type UpdateMealParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, updateMeal, arg.Name, arg.ID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
