// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Completion struct {
	ID             int64         `json:"id"`
	TaskInstanceID int64         `json:"task_instance_id"`
	CompletedBy    string        `json:"completed_by"`
	CompletedAt    sql.NullTime  `json:"completed_at"`
	ActualMins     sql.NullInt64 `json:"actual_mins"`
}

type Meal struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ScheduleSuggestion struct {
	ID          int64         `json:"id"`
	UserMessage string        `json:"user_message"`
	LlmResponse string        `json:"llm_response"`
	WeekOffset  sql.NullInt64 `json:"week_offset"`
	ChangesMade sql.NullBool  `json:"changes_made"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Session struct {
	Token     string       `json:"token"`
	Username  string       `json:"username"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Setting struct {
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ShoppingItem struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Meal          sql.NullString `json:"meal"`
	Quantity      int64          `json:"quantity"`
	WeekStartDate time.Time      `json:"week_start_date"`
	AddedBy       string         `json:"added_by"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type ShoppingItemHistory struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Meal     sql.NullString `json:"meal"`
	LastUsed sql.NullTime   `json:"last_used"`
	UseCount sql.NullInt64  `json:"use_count"`
}

type Task struct {
	ID              int64          `json:"id"`
	Name            string         `json:"name"`
	Category        string         `json:"category"`
	Frequency       string         `json:"frequency"`
	EstimatedMins   int64          `json:"estimated_mins"`
	DefaultAssignee sql.NullString `json:"default_assignee"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type TaskInstance struct {
	ID                    int64          `json:"id"`
	TaskID                int64          `json:"task_id"`
	ScheduledDate         time.Time      `json:"scheduled_date"`
	OriginalScheduledDate sql.NullTime   `json:"original_scheduled_date"`
	AssignedTo            string         `json:"assigned_to"`
	WeekStartDate         time.Time      `json:"week_start_date"`
	BroughtForward        sql.NullBool   `json:"brought_forward"`
	BroughtForwardBy      sql.NullString `json:"brought_forward_by"`
	CountsTowardWeekly    sql.NullBool   `json:"counts_toward_weekly"`
	CreatedAt             sql.NullTime   `json:"created_at"`
}

type User struct {
	Username      string         `json:"username"`
	PasswordHash  sql.NullString `json:"password_hash"`
	IsPasswordSet sql.NullBool   `json:"is_password_set"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
