// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
)

const createSetting = `-- name: CreateSetting :exec
INSERT INTO settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = ?, updated_at = CURRENT_TIMESTAMP
`

type CreateSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) error {
	_, err := q.db.ExecContext(ctx, createSetting, arg.Key, arg.Value)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE settings
SET value = ?, updated_at = CURRENT_TIMESTAMP
WHERE key = ?
`

type UpdateSettingParams struct {
	Value string `json:"value"`
	Key   string `json:"key"`
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateSetting, arg.Value, arg.Key)
	return err
}
