// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shopping.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createShoppingItem = `-- name: CreateShoppingItem :one
INSERT INTO shopping_items (
    name, meal, quantity, week_start_date, added_by
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, meal, quantity, week_start_date, added_by, created_at, updated_at
`

type CreateShoppingItemParams struct {
	Name          string         `json:"name"`
	Meal          sql.NullString `json:"meal"`
	Quantity      int64          `json:"quantity"`
	WeekStartDate time.Time      `json:"week_start_date"`
	AddedBy       string         `json:"added_by"`
}

func (q *Queries) CreateShoppingItem(ctx context.Context, arg CreateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, createShoppingItem,
		arg.Name,
		arg.Meal,
		arg.Quantity,
		arg.WeekStartDate,
		arg.AddedBy,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Meal,
		&i.Quantity,
		&i.WeekStartDate,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldShoppingItems = `-- name: DeleteOldShoppingItems :exec
DELETE FROM shopping_items
WHERE week_start_date < date('now', '-90 days')
`

func (q *Queries) DeleteOldShoppingItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldShoppingItems)
	return err
}

const deleteShoppingItem = `-- name: DeleteShoppingItem :exec
DELETE FROM shopping_items
WHERE id = ?
`

func (q *Queries) DeleteShoppingItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingItem, id)
	return err
}

const deleteShoppingItemsByMealAndWeek = `-- name: DeleteShoppingItemsByMealAndWeek :exec
DELETE FROM shopping_items
WHERE meal IS NOT NULL
  AND LOWER(meal) = LOWER(?1)
  AND week_start_date = ?2
`

type DeleteShoppingItemsByMealAndWeekParams struct {
	Meal          string    `json:"meal"`
	WeekStartDate time.Time `json:"week_start_date"`
}

func (q *Queries) DeleteShoppingItemsByMealAndWeek(ctx context.Context, arg DeleteShoppingItemsByMealAndWeekParams) error {
	_, err := q.db.ExecContext(ctx, deleteShoppingItemsByMealAndWeek, arg.Meal, arg.WeekStartDate)
	return err
}

const getDistinctMeals = `-- name: GetDistinctMeals :many
SELECT DISTINCT meal
FROM shopping_items
WHERE meal IS NOT NULL
ORDER BY meal
`

func (q *Queries) GetDistinctMeals(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var meal sql.NullString
		if err := rows.Scan(&meal); err != nil {
			return nil, err
		}
		items = append(items, meal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemsByMeal = `-- name: GetItemsByMeal :many
SELECT DISTINCT name, meal, quantity
FROM (
    -- Get most recent quantity for each item in this meal
    SELECT name, meal, quantity,
           ROW_NUMBER() OVER (PARTITION BY name ORDER BY created_at DESC) as rn
    FROM shopping_items
    WHERE LOWER(meal) = LOWER(?)
)
WHERE rn = 1
ORDER BY name
`

type GetItemsByMealRow struct {
	Name     string         `json:"name"`
	Meal     sql.NullString `json:"meal"`
	Quantity int64          `json:"quantity"`
}

func (q *Queries) GetItemsByMeal(ctx context.Context, lower string) ([]GetItemsByMealRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemsByMeal, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetItemsByMealRow{}
	for rows.Next() {
		var i GetItemsByMealRow
		if err := rows.Scan(&i.Name, &i.Meal, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShoppingItem = `-- name: GetShoppingItem :one
SELECT id, name, meal, quantity, week_start_date, added_by, created_at, updated_at FROM shopping_items
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetShoppingItem(ctx context.Context, id int64) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, getShoppingItem, id)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Meal,
		&i.Quantity,
		&i.WeekStartDate,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShoppingItemsByWeek = `-- name: ListShoppingItemsByWeek :many
SELECT id, name, meal, quantity, week_start_date, added_by, created_at, updated_at FROM shopping_items
WHERE week_start_date = ?
ORDER BY meal NULLS LAST, name
`

func (q *Queries) ListShoppingItemsByWeek(ctx context.Context, weekStartDate time.Time) ([]ShoppingItem, error) {
	rows, err := q.db.QueryContext(ctx, listShoppingItemsByWeek, weekStartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShoppingItem{}
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Meal,
			&i.Quantity,
			&i.WeekStartDate,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsAutocomplete = `-- name: SearchItemsAutocomplete :many
SELECT DISTINCT name, meal, use_count
FROM shopping_item_history
WHERE LOWER(name) LIKE LOWER(?)
ORDER BY use_count DESC, name
LIMIT 10
`

type SearchItemsAutocompleteRow struct {
	Name     string         `json:"name"`
	Meal     sql.NullString `json:"meal"`
	UseCount sql.NullInt64  `json:"use_count"`
}

func (q *Queries) SearchItemsAutocomplete(ctx context.Context, lower string) ([]SearchItemsAutocompleteRow, error) {
	rows, err := q.db.QueryContext(ctx, searchItemsAutocomplete, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchItemsAutocompleteRow{}
	for rows.Next() {
		var i SearchItemsAutocompleteRow
		if err := rows.Scan(&i.Name, &i.Meal, &i.UseCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMealsAutocomplete = `-- name: SearchMealsAutocomplete :many
SELECT DISTINCT meal, use_count
FROM shopping_item_history
WHERE meal IS NOT NULL
  AND LOWER(meal) LIKE LOWER(?)
ORDER BY use_count DESC, meal
LIMIT 10
`

type SearchMealsAutocompleteRow struct {
	Meal     sql.NullString `json:"meal"`
	UseCount sql.NullInt64  `json:"use_count"`
}

func (q *Queries) SearchMealsAutocomplete(ctx context.Context, lower string) ([]SearchMealsAutocompleteRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMealsAutocomplete, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMealsAutocompleteRow{}
	for rows.Next() {
		var i SearchMealsAutocompleteRow
		if err := rows.Scan(&i.Meal, &i.UseCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShoppingItem = `-- name: UpdateShoppingItem :one
UPDATE shopping_items
SET name = ?,
    meal = ?,
    quantity = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, meal, quantity, week_start_date, added_by, created_at, updated_at
`

type UpdateShoppingItemParams struct {
	Name     string         `json:"name"`
	Meal     sql.NullString `json:"meal"`
	Quantity int64          `json:"quantity"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRowContext(ctx, updateShoppingItem,
		arg.Name,
		arg.Meal,
		arg.Quantity,
		arg.ID,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Meal,
		&i.Quantity,
		&i.WeekStartDate,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertItemHistory = `-- name: UpsertItemHistory :exec
INSERT INTO shopping_item_history (name, meal, last_used, use_count)
VALUES (?, ?, CURRENT_TIMESTAMP, 1)
ON CONFLICT(name, meal) DO UPDATE SET
    last_used = CURRENT_TIMESTAMP,
    use_count = use_count + 1
`

type UpsertItemHistoryParams struct {
	Name string         `json:"name"`
	Meal sql.NullString `json:"meal"`
}

func (q *Queries) UpsertItemHistory(ctx context.Context, arg UpsertItemHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemHistory, arg.Name, arg.Meal)
	return err
}
