// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks_with_next.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getTasksWithNextScheduled = `-- name: GetTasksWithNextScheduled :many
SELECT
    t.id,
    t.name,
    t.category,
    t.frequency,
    t.default_assignee,
    t.estimated_mins,
    t.created_at,
    t.updated_at,
    COALESCE((SELECT scheduled_date FROM task_instances
     WHERE task_id = t.id
       AND scheduled_date >= date('now')
       AND id NOT IN (SELECT task_instance_id FROM completions)
     ORDER BY scheduled_date
     LIMIT 1), NULL) as next_scheduled_date,
    COALESCE((SELECT assigned_to FROM task_instances
     WHERE task_id = t.id
       AND scheduled_date >= date('now')
       AND id NOT IN (SELECT task_instance_id FROM completions)
     ORDER BY scheduled_date
     LIMIT 1), NULL) as next_assigned_to
FROM tasks t
ORDER BY t.name
`

type GetTasksWithNextScheduledRow struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	Category          string         `json:"category"`
	Frequency         string         `json:"frequency"`
	DefaultAssignee   sql.NullString `json:"default_assignee"`
	EstimatedMins     int64          `json:"estimated_mins"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	NextScheduledDate interface{}    `json:"next_scheduled_date"`
	NextAssignedTo    interface{}    `json:"next_assigned_to"`
}

func (q *Queries) GetTasksWithNextScheduled(ctx context.Context) ([]GetTasksWithNextScheduledRow, error) {
	rows, err := q.db.QueryContext(ctx, getTasksWithNextScheduled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksWithNextScheduledRow{}
	for rows.Next() {
		var i GetTasksWithNextScheduledRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Frequency,
			&i.DefaultAssignee,
			&i.EstimatedMins,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextScheduledDate,
			&i.NextAssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
