// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM tasks
`

func (q *Queries) CountTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (name, category, frequency, estimated_mins, default_assignee)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, category, frequency, estimated_mins, default_assignee, created_at, updated_at
`

type CreateTaskParams struct {
	Name            string         `json:"name"`
	Category        string         `json:"category"`
	Frequency       string         `json:"frequency"`
	EstimatedMins   int64          `json:"estimated_mins"`
	DefaultAssignee sql.NullString `json:"default_assignee"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Name,
		arg.Category,
		arg.Frequency,
		arg.EstimatedMins,
		arg.DefaultAssignee,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Frequency,
		&i.EstimatedMins,
		&i.DefaultAssignee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT DISTINCT category FROM tasks
ORDER BY category
`

func (q *Queries) GetCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, name, category, frequency, estimated_mins, default_assignee, created_at, updated_at FROM tasks
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Frequency,
		&i.EstimatedMins,
		&i.DefaultAssignee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, name, category, frequency, estimated_mins, default_assignee, created_at, updated_at FROM tasks
ORDER BY category, name
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Frequency,
			&i.EstimatedMins,
			&i.DefaultAssignee,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCategory = `-- name: ListTasksByCategory :many
SELECT id, name, category, frequency, estimated_mins, default_assignee, created_at, updated_at FROM tasks
WHERE category = ?
ORDER BY name
`

func (q *Queries) ListTasksByCategory(ctx context.Context, category string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Frequency,
			&i.EstimatedMins,
			&i.DefaultAssignee,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET name = ?, category = ?, frequency = ?, estimated_mins = ?, default_assignee = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, category, frequency, estimated_mins, default_assignee, created_at, updated_at
`

type UpdateTaskParams struct {
	Name            string         `json:"name"`
	Category        string         `json:"category"`
	Frequency       string         `json:"frequency"`
	EstimatedMins   int64          `json:"estimated_mins"`
	DefaultAssignee sql.NullString `json:"default_assignee"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Name,
		arg.Category,
		arg.Frequency,
		arg.EstimatedMins,
		arg.DefaultAssignee,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Frequency,
		&i.EstimatedMins,
		&i.DefaultAssignee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
